affeldt-aist/monae

fail_lib.v
hierarchy.v
monad_model.v

- examples of computation with shift/reset
- add references for examples and laws

proof-reading about control monads

---

.travis.yml
Makefile
README.org
_CoqProject
altprob_model.v
category.v
example_monty.v
fail_lib.v
fmt_lifting.v
gcm_model.v
hierarchy.v
impredicative_set/_CoqProject
impredicative_set/ifail_lib.v
impredicative_set/ifmt_lifting.v
impredicative_set/ihierarchy.v
impredicative_set/imonad_composition.v
impredicative_set/imonad_lib.v
impredicative_set/imonad_model.v
impredicative_set/imonad_transformer.v
impredicative_set/iparametricity_codensity.v
monad_composition.v
monad_lib.v
monad_model.v
monad_transformer.v
opam
parametricity_codensity.v
proba_lib.v
proba_monad_model.v
smallstep.v
state_lib.v

mathcomp-analysis and infotheo are not yet available as opam packages.

test compilation with mathcomp 1.11.0

---

Makefile
fail_lib.v
fmt_lifting.v
hierarchy.v
impredicative_set/ifail_lib.v
impredicative_set/ifmt_lifting.v
impredicative_set/ihierarchy.v
impredicative_set/imonad_transformer.v
monad_transformer.v
opam

Example 29, fixes, naming convention

---

fmt_lifting.v
impredicative_set/ifmt_lifting.v
impredicative_set/imonad_transformer.v
monad_transformer.v

new monad transformers with their functorial version:
- output, environment
complete example 29 with the lifting of sigma-operations along
- the output monad transformer
- the environment monad transformers
complete example 31 with the lifting of handle along four
monad transformers

complete examples 29 and 31

---

fmt_lifting.v
impredicative_set/ifmt_lifting.v
impredicative_set/imonad_model.v
impredicative_set/imonad_transformer.v

Examples 30 32

---

altprob_model.v
category.v
fmt_lifting.v
gcm_model.v
impredicative_set/ifmt_lifting.v
impredicative_set/imonad_model.v
impredicative_set/imonad_transformer.v
impredicative_set/iparametricity_codensity.v
monad_model.v
monad_transformer.v
parametricity_codensity.v

leftover of scsl -> lub renaming

minor edits

---

.travis.yml
README.org
_CoqProject
gcm_model.v
hierarchy.v
impredicative_set/_CoqProject
impredicative_set/ihierarchy.v
monad_model.v
opam

Fix the build with coq-8.12.0 by avoiding notations at several mixin definitions.
[Environment]
coq : github, v8.12 branch
mathcomp : 1.11.0
analysis: github master

Compatibility with Coq 8.12

---

README.org
_CoqProject
category.v
example_monad_transformer.v
fmt_lifting.v
hierarchy.v
impredicative_set/_CoqProject
impredicative_set/iexample_monad_transformer.v
impredicative_set/ifmt_lifting.v
impredicative_set/ihierarchy.v
impredicative_set/imonad_lib.v
impredicative_set/imonad_model.v
impredicative_set/imonad_transformer.v
impredicative_set/itrace_lib.v
monad_lib.v
monad_model.v
monad_transformer.v
monae_lib.v
trace_lib.v

- hierarchy:
+ remove loopstatecont
+ add failStateMonad
- introduce the proof_irr shortcut
@davidnowak

refactoring (wip)

---

example_quicksort.v

minor progress in reproducing the proof by Mu

Mu's quicksort

---

.github/workflows/docker-action.yml
README.md
_CoqProject
altprob_model.v
category.v
coq-monae.opam
gcm_model.v
hierarchy.v
index.md
meta.yml
monad_model.v
proba_lib.v
proba_monad_model.v

Prove an example to be included in the paper; (almost) based on the ~~semilattconv~~ ~~master branch of~~ infotheo 0.3
Waiting for the opam package of infotheo 0.3 for the CI to succeed.

Arbcoin spec convexity + compatibility infotheo 0.3

---

altprob_model.v

Some horrible proofs in altprob_model are shortened in this PR.

shorten proofs in altprob_model.v

---

gcm_model.v

proba_monad_model and F0 -| U0 are the same thing

F0U0 and prob

---

proba_lib.v
proba_monad_model.v

This PR contains changes in proba_lib.v needed to follow boolean_prob branch of infotheo.

follow boolean_prob branch of infotheo

---

example_transformer.v
fail_lib.v
hierarchy.v
impredicative_set/iexample_transformer.v
impredicative_set/ifail_lib.v
impredicative_set/ifmt_lifting.v
impredicative_set/ihierarchy.v
impredicative_set/imonad_composition.v
impredicative_set/imonad_lib.v
impredicative_set/imonad_model.v
impredicative_set/imonad_transformer.v
impredicative_set/imonae_lib.v
impredicative_set/iparametricity_codensity.v
impredicative_set/istate_lib.v
impredicative_set/itrace_lib.v
meta.yml
monad_composition.v
monad_model.v
monad_transformer.v

Monae hb impred

---

_CoqProject
category_ext.v

Introduce slice categories and product categories.
This will be a first step towards concretizing more constructions and monoidal categories.

define slice category and product category

---

hierarchy.v
impredicative_set/ihierarchy.v
impredicative_set/imonad_lib.v
monad_lib.v

move Monad_of_ret_bind builder to hierarchy

---

example_array.v

- renamed dguard to dassert
- organize example_array.v using sections
- adjust implicit arguments

cleaning wip

---

example_array.v
example_spark.v
fail_lib.v
impredicative_set/ifail_lib.v

move insert and perm lemmas out of example_array.v

---

.github/workflows/docker-action.yml
README.md
_CoqProject
altprob_model.v
category.v
coq-monae.opam
example_monty.v
fail_lib.v
gcm_model.v
hierarchy.v
impredicative_set/_CoqProject
impredicative_set/iparametricity_codensity.v
meta.yml
proba_lib.v

trying to use infotheo_hb

---

_CoqProject
example_typed_store.v
typed_store_model.v

add execution of some examples

coqgen examples executable in monad_model

---

example_typed_store.v

No change in the actual proofs, only in the intermediate goals printed.

::: for Cons in proofs
